/**
 * Generates `src/styles/theme.css` from `src/tokens/index.ts` (decision 0005).
 *
 *   bun run build:theme          write the file
 *   bun run check:theme          exit 1 if the file is stale
 *
 * Output shape:
 *   @theme { ... }          static palette values, Tailwind namespaces
 *   @theme inline { ... }   role utilities that alias runtime custom properties
 *   :root / [data-theme]    light and dark role values
 *   [data-register]         which accent scale the register uses
 *
 * Every token family gets one `emit*` function below. Add a function when a
 * new token file lands; keep the file order stable so diffs stay readable.
 */

import {
  absolutes,
  colorSteps,
  defaultRegister,
  palette,
  registerAccent,
  registers,
  resolveColor,
  roles,
  statuses,
  type ColorRef,
  type PaletteName,
  type Register,
  type Theme,
  type ThemeRoles,
} from "../src/tokens/index.ts";

const OUTPUT = new URL("../src/styles/theme.css", import.meta.url);
const RUNTIME_PREFIX = "--el";

const kebab = (s: string): string => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

const line = (name: string, value: string): string => `  ${name}: ${value};`;

/** Role name -> CSS variable suffix, flattening the nested `status` map. */
function flattenRoles(r: ThemeRoles): Array<[string, ColorRef]> {
  const out: Array<[string, ColorRef]> = [];
  for (const [key, value] of Object.entries(r)) {
    if (key === "status") continue;
    out.push([kebab(key), value as ColorRef]);
  }
  for (const status of statuses) {
    for (const [part, value] of Object.entries(r.status[status])) {
      out.push([`status-${status}-${part}`, value]);
    }
  }
  return out;
}

function emitColorPalette(): string[] {
  const out: string[] = [];
  out.push("  /* Colour: palette (0001). Tailwind defaults are cleared so only tokens exist. */");
  out.push(line("--color-*", "initial"));
  for (const [name, value] of Object.entries(absolutes)) out.push(line(`--color-${name}`, value));
  for (const name of Object.keys(palette) as PaletteName[]) {
    for (const step of colorSteps) out.push(line(`--color-${kebab(name)}-${step}`, palette[name][step]));
  }
  return out;
}

function emitColorRoleAliases(): string[] {
  const out: string[] = [];
  out.push("  /* Colour: roles resolve at runtime by theme and register. */");
  for (const [name] of flattenRoles(roles.light)) {
    out.push(line(`--color-${name}`, `var(${RUNTIME_PREFIX}-${name})`));
  }
  for (const step of colorSteps) {
    out.push(line(`--color-accent-${step}`, `var(${RUNTIME_PREFIX}-accent-${step})`));
  }
  return out;
}

function emitThemeBlock(theme: Theme): string[] {
  return flattenRoles(roles[theme]).map(([name, ref]) =>
    line(`${RUNTIME_PREFIX}-${name}`, resolveColor(ref)),
  );
}

function emitRegisterBlock(register: Register): string[] {
  const scale = kebab(registerAccent[register]);
  return colorSteps.map((step) =>
    line(`${RUNTIME_PREFIX}-accent-${step}`, `var(--color-${scale}-${step})`),
  );
}

function render(): string {
  const parts: string[] = [];
  parts.push("/* Generated by scripts/build-theme.ts from src/tokens/. Do not edit by hand. */");
  parts.push("");
  parts.push("@theme {", ...emitColorPalette(), "}");
  parts.push("");
  parts.push("@theme inline {", ...emitColorRoleAliases(), "}");
  parts.push("");
  parts.push("/* Theme: light is the default; dark follows the OS unless data-theme pins it. */");
  parts.push(':root, [data-theme="light"] {', ...emitThemeBlock("light"), "}");
  parts.push("");
  parts.push("@media (prefers-color-scheme: dark) {");
  parts.push('  :root:not([data-theme="light"]) {');
  parts.push(...emitThemeBlock("dark").map((l) => `  ${l}`));
  parts.push("  }");
  parts.push("}");
  parts.push("");
  parts.push('[data-theme="dark"] {', ...emitThemeBlock("dark"), "}");
  parts.push("");
  parts.push(`/* Register: accent follows the nearest data-register; ${defaultRegister} is the default. */`);
  for (const register of registers) {
    const selector =
      register === defaultRegister
        ? `:root, [data-register="${register}"]`
        : `[data-register="${register}"]`;
    parts.push(`${selector} {`, ...emitRegisterBlock(register), "}");
    parts.push("");
  }
  return `${parts.join("\n").trimEnd()}\n`;
}

const css = render();
const check = process.argv.includes("--check");
const current = await Bun.file(OUTPUT).text().catch(() => "");

if (check) {
  if (current === css) {
    console.log("theme.css is up to date");
  } else {
    console.error("theme.css is stale. Run `bun run build:theme` and commit the result.");
    process.exit(1);
  }
} else {
  await Bun.write(OUTPUT, css);
  console.log(`wrote ${OUTPUT.pathname}`);
}
