/**
 * Colour tokens. Source of truth for every colour in the system.
 *
 * Structure (see docs/decisions/0001-colour-palette.md and
 * docs/foundations/colour.md):
 *
 * - `palette`  raw scales, 50 to 950, named by role never by hue. The hex
 *              values are generated by `bun run build:palette` from an OKLCH
 *              recipe in `scripts/build-palette.ts`; edit the recipe, not
 *              the hex, when a hue changes.
 * - `roles`    semantic aliases for surfaces, text, borders and status,
 *              resolved per theme (light, dark).
 * - `registers` which accent scale each audience register uses.
 *
 * Components never reference `palette` directly for surfaces or text; they
 * use the role utilities Tailwind generates (`bg-canvas`, `text-fg-muted`, ...).
 */

import type { Hex } from "../utils/color.ts";

export const colorSteps = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;
export type ColorStep = (typeof colorSteps)[number];
export type ColorScale = Readonly<Record<ColorStep, Hex>>;

/** Generated by `bun run build:palette`. Do not hand-edit individual steps. */
export const palette = {
  brand: {
    50: "#ECFAFE",
    100: "#D6F3FC",
    200: "#B0E5F5",
    300: "#82D2E9",
    400: "#3FB5D2",
    500: "#0995B2",
    600: "#007890",
    700: "#006073",
    800: "#024B5A",
    900: "#003743",
    950: "#00242D",
  },
  accentB2b: {
    50: "#F4F7FE",
    100: "#E6EDFE",
    200: "#CCDAFF",
    300: "#ABC3FE",
    400: "#7E9FFF",
    500: "#5B7DEB",
    600: "#4362CB",
    700: "#324BA9",
    800: "#253A88",
    900: "#1A2A65",
    950: "#0F1B45",
  },
  accentB2c: {
    50: "#FEF3F8",
    100: "#FEE5F0",
    200: "#FFC9E1",
    300: "#FFA4CF",
    400: "#ED76B3",
    500: "#D44996",
    600: "#B42C7B",
    700: "#941762",
    800: "#760D4D",
    900: "#580938",
    950: "#3C0425",
  },
  success: {
    50: "#EFFAF0",
    100: "#DCF4E0",
    200: "#BCE8C4",
    300: "#96D6A3",
    400: "#64BB79",
    500: "#2E9E52",
    600: "#03823A",
    700: "#02672D",
    800: "#005121",
    900: "#003C17",
    950: "#00280C",
  },
  warning: {
    50: "#FEF5EB",
    100: "#FEE9D0",
    200: "#F9D4A7",
    300: "#EEB976",
    400: "#D89532",
    500: "#B67703",
    600: "#935F02",
    700: "#754B01",
    800: "#5C3A01",
    900: "#452A00",
    950: "#2E1A00",
  },
  danger: {
    50: "#FEF4F3",
    100: "#FFE6E3",
    200: "#FFCDC6",
    300: "#FEABA1",
    400: "#F9776C",
    500: "#E24942",
    600: "#C02B28",
    700: "#9F1417",
    800: "#7F090E",
    900: "#5E0809",
    950: "#410404",
  },
  info: {
    50: "#F9F5FF",
    100: "#F2E8FF",
    200: "#E5D0FF",
    300: "#D5B2FE",
    400: "#BA8BED",
    500: "#9E66D7",
    600: "#834CB7",
    700: "#6A3898",
    800: "#532979",
    900: "#3D1E5A",
    950: "#28123D",
  },
  neutral: {
    50: "#F9F6F2",
    100: "#EFECE8",
    200: "#DDDAD6",
    300: "#C6C4C0",
    400: "#A7A4A0",
    500: "#888682",
    600: "#6E6B68",
    700: "#575552",
    800: "#44423F",
    900: "#32302D",
    950: "#211F1C",
  },
} as const satisfies Record<string, ColorScale>;

export type PaletteName = keyof typeof palette;

export const absolutes = {
  white: "#FFFFFF",
  black: "#000000",
} as const satisfies Record<string, Hex>;

/** A reference into the palette, resolved by the theme generator. */
export type ColorRef =
  | { readonly scale: PaletteName; readonly step: ColorStep }
  | { readonly absolute: keyof typeof absolutes };

const ref = (scale: PaletteName, step: ColorStep): ColorRef => ({ scale, step });
const abs = (absolute: keyof typeof absolutes): ColorRef => ({ absolute });

export const themes = ["light", "dark"] as const;
export type Theme = (typeof themes)[number];

export const statuses = ["success", "warning", "danger", "info"] as const;
export type Status = (typeof statuses)[number];

export interface StatusRoles {
  /** Text and icons. AA on `bg` and on the theme canvas. */
  readonly fg: ColorRef;
  /** Tinted background for banners, badges and rows. */
  readonly bg: ColorRef;
  /** Border for the tinted background. */
  readonly border: ColorRef;
  /** Solid fill (buttons, strong badges). Carries `fgInverse`. */
  readonly solid: ColorRef;
}

export interface ThemeRoles {
  /** Page background. */
  readonly canvas: ColorRef;
  /** Default component background (cards, inputs, sheets). Elevation 1. */
  readonly surface: ColorRef;
  /** Raised above surface (popovers, menus). Elevation 2. */
  readonly surfaceRaised: ColorRef;
  /** Modal and dialog panels. Elevation 3. */
  readonly surfaceOverlay: ColorRef;
  /** Recessed areas: wells, table headers, code. */
  readonly surfaceSunken: ColorRef;
  /** Primary text. Utilities read `text-fg`, `text-fg-muted`. */
  readonly fg: ColorRef;
  /** Secondary text: labels, captions. AA on every surface. */
  readonly fgMuted: ColorRef;
  /** Tertiary text: placeholders, hints. AA on canvas and surface. */
  readonly fgSubtle: ColorRef;
  /** Text on solid brand, accent and status fills. White in both themes. */
  readonly fgInverse: ColorRef;
  /** Default hairline. */
  readonly border: ColorRef;
  /** Input and control boundaries. 3:1 against canvas and surface (WCAG 1.4.11). */
  readonly borderStrong: ColorRef;
  /** Focus ring. AA (3:1) against canvas and surface. */
  readonly ring: ColorRef;
  /** Inline links. AA on canvas and surface. */
  readonly link: ColorRef;
  /** Primary action fill. Carries `fgInverse`. */
  readonly brandSolid: ColorRef;
  /** Brand as text or icon on canvas and surface. */
  readonly brandFg: ColorRef;
  /** Brand tint for selected rows, chips, subtle emphasis. */
  readonly brandBg: ColorRef;
  readonly status: Readonly<Record<Status, StatusRoles>>;
}

const statusRoles = (scale: Status, theme: Theme): StatusRoles =>
  theme === "light"
    ? { fg: ref(scale, 700), bg: ref(scale, 50), border: ref(scale, 200), solid: ref(scale, 600) }
    : { fg: ref(scale, 300), bg: ref(scale, 950), border: ref(scale, 800), solid: ref(scale, 600) };
// Solid fills stay at 600 in both themes: it is the first step that carries
// white text at AA, and white is `fgInverse` in both themes for that reason.

const statusSet = (theme: Theme): Readonly<Record<Status, StatusRoles>> => ({
  success: statusRoles("success", theme),
  warning: statusRoles("warning", theme),
  danger: statusRoles("danger", theme),
  info: statusRoles("info", theme),
});

export const roles: Readonly<Record<Theme, ThemeRoles>> = {
  light: {
    canvas: ref("neutral", 50),
    surface: abs("white"),
    surfaceRaised: abs("white"),
    surfaceOverlay: abs("white"),
    surfaceSunken: ref("neutral", 100),
    fg: ref("neutral", 950),
    fgMuted: ref("neutral", 700),
    fgSubtle: ref("neutral", 600),
    fgInverse: abs("white"),
    border: ref("neutral", 200),
    borderStrong: ref("neutral", 500),
    ring: ref("brand", 500),
    link: ref("brand", 700),
    brandSolid: ref("brand", 600),
    brandFg: ref("brand", 700),
    brandBg: ref("brand", 50),
    status: statusSet("light"),
  },
  dark: {
    canvas: ref("neutral", 950),
    surface: ref("neutral", 900),
    surfaceRaised: ref("neutral", 800),
    surfaceOverlay: ref("neutral", 800),
    surfaceSunken: abs("black"),
    fg: ref("neutral", 50),
    fgMuted: ref("neutral", 200),
    fgSubtle: ref("neutral", 300),
    fgInverse: abs("white"),
    border: ref("neutral", 800),
    borderStrong: ref("neutral", 500),
    ring: ref("brand", 400),
    link: ref("brand", 300),
    brandSolid: ref("brand", 600),
    brandFg: ref("brand", 300),
    brandBg: ref("brand", 950),
    status: statusSet("dark"),
  },
};

/**
 * Audience registers (MISSION.md: one brand, two registers). The `accent`
 * scale in Tailwind resolves to one of these depending on the nearest
 * `data-register` ancestor. B2C is the default because it is the public face.
 */
export const registers = ["b2c", "b2b"] as const;
export type Register = (typeof registers)[number];
export const defaultRegister: Register = "b2c";

export const registerAccent: Readonly<Record<Register, PaletteName>> = {
  b2c: "accentB2c",
  b2b: "accentB2b",
};

/** Resolve a reference to its hex value. */
export function resolveColor(color: ColorRef): Hex {
  return "absolute" in color ? absolutes[color.absolute] : palette[color.scale][color.step];
}
